sudo: required

services:
  - docker

before_install:
  - docker build -t alexanderbudnikov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alexanderbudnikov/docker-react npm run test
